---
title: Pika-Quiz Notes
format: html
---

# Questions

- You've got a long drive ahead of you. What album sounds best for the road?
    - Smooth jazz
        - Emolga
        - Pichu
    - Alternative rock
        - Togdemaru
        - Mimikyu
    - Rap
        - Morpeko
        - Pawmo
    - Indie/pop
        - Dedenne
        - Plusle/Minun
    - Throwback classics!
        - Pikachu
        - Pachirisu

- Good morning! What's for breakfast?
    - Eggs with breakfast meat!
        - Pikachu
        - Pawmo
    - Pancakes. Stack em high!
        - Morpeko
        - Emolga
        - Pichu
    - Acai bowl
        - Pachirisu
    - Quick bagel or toast
        - Togdemaru
        - Mimikyu
    - Running on coffee
        - Plusle/Minun
        - Dedenne

- You go to the theatre. Which movie are you watching?
    - Anything with guns, sex, or violence!
        - Morpeko
        - Pachirisu
    - Something animated like Cars 3
        - Pawmo
        - Pichu
    - Horror movie
        - Mimikyu
        - Dedenne
    - Sad, romantic
        - Plusle/Minun
        - Emolga
    - Something funny like The Hangover
        - Pikachu
        - Togdemaru
    
const quiz = {
  totalQuestions: 5,
  questions: [
  {
    id: 1,
    question: "You've got a busy day ahead of you! What sort of breakfast will help you get started for the day?",
    answers: [
      { text: "Nothing like a good ol' balanced breakfast: two eggs, hashbrowns, bacon, and some OJ.", pikaClones:["Pikachu", "Togdemaru"] },
      { text: "Pancakes with berries and syrup on top! Stack em as high as the sky.", pikaClones: ["Emolga", "Morpeko"] },
      { text: "A muffin, a yogurt parfait, and enough sugar to make me think it's healthy.", pikaClones: ["Dedenne"] },
      { text: "I probably already woke up late. Catch me running out of the house with a piece of burnt toast in my mouth.", pikaClones: ["Pichu"] },
      { text: "*accidentally slept through the alarm*", pikaClones: ["Pachirisu","Pawmot"] },
      { text: "Coffee is my breakfast, lunch, and best friend. Add existential dread for flavor.", pikaClones: ["Plusle/Minun", "Mimikyu"]}
    ] 
  },
  {
    id: 2,
    question: "You don't know that many people at your friend's party. Which best describes you?",
    answers: [
      { text: "*snarf..gobble..munch..* \"Oh did you say something?\" You were too busy enjoying the food to notice anyone else there... ", pikaClones: ["Morpeko"] },
      { text: "You're naturally charming and are looking forward to this opportunity to meet new friends", pikaClones: ["Pikachu", "Plusle/Minun","Pawmot"] },
      { text: "You are feeling a bit reserved and mostly just stick to talking with the few friends you already know.", pikaClones: ["Togdemaru"] },
      { text: "You wore a costume even though it was nowhere implied that it was a costume party", pikaClones: ["Mimikyu"] },
      { text: "\"mom pick me up I'm scared\"", pikaClones: ["Pichu"] },
      { text: "You are now wishing you had just stayed home and played league instead", pikaClones: ["Pachirisu", "Dedenne"]},
      { text: "You’re swooping in and out of conversations, making your presence known without staying too long", pikaClones:["Emolga"] }
    ]
  },
  {
    id: 3,
    question: "You've got a huge midterm exam coming up next week! What's your game plan?",
    answers: [
      { text: "Study group time! Mostly for moral support and snacks, but hey, it counts.", pikaClones: ["Plusle/Minun", "Pikachu", "Pawmot"] },
      { text: "Color-coded notecards and a three-step plan. Who needs spontaneity when you're this organized?", pikaClone: ["Dedenne"] },
      { text: "It's time to lock-in. You find a quiet spot on the third floor of the library, put on your headphones, and tune into some \"24/7 lofi hip hop beats to study and chill to\"", pikaClones: ["Togedemaru", "Mimikyu"] },
      { text: "Snacks are the key to knowledge. The more snacks, the more brain power. It's science.", pikaClones: ["Morpeko"] },
      { text: "You go to the library but you end up playing Pokemon Go the whole time on your phone...", pikaClones: ["Emolga", "Pachirisu", "Pichu"]}
    ]
  },
  {
    id: 4,
    question: "It's vacation time! What are we planning?",
    answers: [
      { text: "A tropical beach getaway! I can't wait to soak up the sun and listen to the sound of crashing waves", pikaClones: ["Pikachu", "Dedenne"] },
      { text: "I'm hitting up my BFF ASAP! It's not a proper vacation unless I'm in good company", pikaClones: ["Plusle/Minun", "Pichu"] },
      { text: "Las Vegas baby! I have a crippling gambling addiction!", pikaClones: ["Pachirisu", "Emolga"] },
      { text: "I think I'd rather just stay home and binge all the lord of the ring movies again...", pikaClones: ["Mimikyu"] },
      { text: "Time to go hiking in the mountains. I love exploring nature and finding great views", pikaClones: ["Pawmot", "Togdemaru"]},
      { text: "Going on a food tour in a new city. Snacks are the priority, sightseeing comes second!", pikaClones: ["Morpeko"]}
    ]
  }
  ],
}
